# Generated by Django 5.1.4 on 2026-07-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectlanguage_remove_project_tech_stack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='used_open_source',
        ),
    ]
