# Generated by Django 5.1.4 on 2026-08-26 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectlanguage_remove_project_tech_stack_and_more'),
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SixMonthProjectRanking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='six_month_ranking', serialize=False, to='projects.project')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=30)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('commits', models.PositiveIntegerField(default=0)),
                ('pull_requests', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
            ],
            options={
                'ordering': ('-total_score', 'project__name', 'project_id'),
            },
        ),
        migrations.AlterModelOptions(
            name='projectranking',
            options={'ordering': ('-total_score', 'project__name', 'project_id')},
        ),
        migrations.RemoveField(
            model_name='projectranking',
            name='rank',
        ),
    ]
