# Generated by Django 5.1.15 on 2026-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_id', models.BigIntegerField(unique=True)),
                ('owner', models.CharField(max_length=120)),
                ('repo', models.CharField(max_length=120)),
                ('full_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=60, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('html_url', models.URLField(max_length=500)),
                ('github_updated_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'unique_together': {('owner', 'repo')},
            },
        ),
    ]
