# Generated by Django 5.1.4 on 2026-08-19 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingRepositorySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(unique=True)),
            ],
            options={
                'ordering': ('-week_start',),
            },
        ),
        migrations.CreateModel(
            name='TrendingRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_id', models.PositiveBigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=300)),
                ('html_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=100)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField()),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='trending.trendingrepositoryselection')),
            ],
            options={
                'ordering': ('-selection__week_start', 'position', 'github_id'),
                'constraints': [models.UniqueConstraint(fields=('selection', 'position'), name='trending_selection_position_uniq')],
            },
        ),
    ]
