# Generated by Django 5.1.4 on 2026-08-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendingrepository',
            options={},
        ),
    ]
