# Generated by Django 5.1.4 on 2026-08-26 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractivity_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='SixMonthUserRanking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='six_month_ranking', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_score', models.PositiveBigIntegerField(default=0)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('commits', models.PositiveIntegerField(default=0)),
                ('pull_requests', models.PositiveIntegerField(default=0)),
                ('issues', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
